#!/usr/bin/env php
<?php

declare(strict_types=1);

/*
 * This file is part of the coolephp/skeleton.
 *
 * (c) guanguans <ityaozm@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled.
 */

! defined('BASE_PATH') && define('BASE_PATH', __DIR__);

require BASE_PATH.'/../../vendor/autoload.php';

app('console')->run();
